name: Enectiva
markdown: redcarpet
highlighter: true

url: http://enectiva.cz

gems:
- jekyll-compass
- jekyll-assets

assets:
  dirname: assets-web
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
#  js_compressor: uglifier
#  css_compressor: sass
  gzip: 
    - text/css
    - application/javascript
    - image/svg+xml
    - application/vnd.ms-fontobject
    - application/font-woff
    - application/x-font-woff
    - application/font-stnt
    - application/octet-stream

exclude:
- readme.md
- Gemfile
- Gemfile.lock

permalink:  /:categories/:year/:month/:title

paginate: 5
paginate_path: /blog/page-:num
paginate_per_category: true
default_category: cs

authorized_locales: [cs, en, it]
default_locale: cs

cs:
  prev: Novější
  next: Starší
en:
  prev: Older
  next: Newer

prose:
  rooturl: ""
  siteurl: "http://enectiva.cz/"
  media: "img"
  metadata:
    cs:
      - name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Dodatečná klíčová slova"
          placeholder: "Mělo by začínat ,"
    en:
      - name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    it:
      - name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    cs/blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          placeholder: "Název článku"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Autor"
          placeholder: "(z /config/authors.yml)"
      - name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Dodatečná klíčová slova"
          placeholder: "Mělo by začínat ,"
    en/blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          placeholder: "Post title"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Author"
          placeholder: "(from /config/authors.yml)"
      - name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"